### ISSUE TITLE
Fail to verify EIP1167 Clone contract

### ISSUE THREAD

**Issue by zhengxunWu1** [rkalis/truffle-plugin-verify#126]
I deployed the contract using [clone model](https://docs.openzeppelin.com/contracts/4.x/api/proxy#minimal_clones), the cloned contract has no construction and construction parameter is passed through initialize function. 
I am using `truffle run verify ContractName@{deployedAddr} --network kovan --debug` but I got `Fail - Unable to verify`

Is it possible to verify a cloned contract deployed through a factory on etherscan? I haven't even figured out how to verify it even manually.. Do I need to encode constructor parameter as what I passed through initialize function? Do I need to verify implementation contract? Could you give some hint? Would be very appreciated.

Using `truffle-plugin-verify v0.5.18`.

**Comment by rkalis** [comment]
Hmm interesting. I'm not too familiar with EIP1167 Clones. I'm imagining that the "Clones.sol" contract includes some constructor args that it passes to the clone (even if the implementation doesn't have any). This needs some more research. Any help is definitely welcome here as well!

**Comment by rkalis** [comment]
I see. After looking into it a "Clone" contract has a very specific EVM bytecode without any corresponding Solidity source code attached to it. As such it's impossible to "verify" the Clone contract. I can imagine that Etherscan already has support for Clone contracts or otherwise will most likely add support in the future to reflect that a certain contract is an EIP1167 Clone of a different contract (cc @Enigmatic331).

In any case you need to verify the *implementation* contract. I'll close this issue now, since there's no way to verify the Clone contract. Please feel free te re-open this issue or open a new issue if you run into issues while verifying the implementation contract.
