### ISSUE TITLE
Support for OKLINK (OkEx Chain)

### ISSUE THREAD

**Issue by ghost** [rkalis/truffle-plugin-verify#136]
Please add support for OKLINK.
The current issue
Etherscan has no support for network mainnet with chain id 66

**Comment by rkalis** [comment]
Since they have a very differeny API interface from Etherscan and its derived platforms, this is a significant amount of work to integrate into this code base. It might be possible to pick this up *after* BlockScout / Sourcify support, but adding support for those platforms is also not a very high priority, so while I won't close this issue outright I have to say that there's a high chance that this won't be implemented for a long time (if at all).

**Comment by rkalis** [comment]
With Sourcify support added (and the necessary refactors done), this has become easier to add, since a OkLinkVerifier can be added to src/verifiers. Will accept PRs for this.

**Comment by rkalis** [comment]
Since Truffle is being sunset, I don't plan to add new features, so I'm closing this issue.
