### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by travisdmathis** [rkalis/truffle-plugin-verify#16]
Every time I try to verify I get "Invalid API Key" it worked 1 time, 2nd time it fails every time.

```
cd-bank truffle run verify CDRW --network goerli
> Warning: possible unsupported (undocumented in help) command line option: --network
Verifying CDRW
Invalid API Key

Failed to verify 1 contract(s): CDRW


```

**Comment by rkalis** [comment]
I cloned your repository, ran your migrations on goerli, and then I verified it. I redeployed and reverified a few times, but I could not reproduce your error. I did see that you have your mnemonic and API key in your GitHub repo, rather than in a private `.env` file. It might be that Etherscan automatically disables API keys if they are compromised (i.e. available to the public), but again I was able to verify using the API key in your repo so that doen't seem likely. I'm not sure how to proceed with this as I can't reproduce the bug. Do you have clear steps to reproduce that you have been able to follow on different machines with similar results?

**Comment by travisdmathis** [comment]
@rkalis i think you might be right.. because it would work 1 time then fail.. was for a ETHBoston and was a burner wallet so that didn't even cross my mind....

**Comment by rkalis** [comment]
Is it working correctly for you now?

**Comment by rkalis** [comment]
Closing this as I haven't heard any more complaints on this.

**Comment by dobpp** [comment]
On Heco chain, I am gettins same issue

**Comment by shaunrd0** [comment]
Having this problem too, API key, code, contract address is all showing up right when I pass `--debug` option, but still getting Invalid API Key just as OP shows. I'm on ropsten. [Here is my reposityory](https://gitlab.com/shaunrd0/karma/-/tree/upgradeable-karma), the issue I'm having is at the latest commit is on the `upgradeable-karma` branch. I'll update if I find a solution. Any luck, @dobpp ?

**Comment by rkalis** [comment]
Does it change anything if you create a new API key and use that?

**Comment by shaunrd0** [comment]
It seems like I just happened to be using endpoints that were under maintenance at that time, so things are fine now on all endpoints. Still unable to verify my development branch. What is interesting to me though, is I can verify my `Migrations` contract, just not the `Karma` contract  -

```
$ npx truffle run verify Migrations --license MIT --network ropsten
Verifying Migrations
Pass - Verified: https://ropsten.etherscan.io/address/0xE2C05A757fD9C810160a783D72C8f6D60C32983F#contracts
Successfully verified 1 contract(s).
$ npx truffle run verify  Karma --license MIT --network ropsten
Verifying Karma
Fail - Unable to verify
Failed to verify 1 contract(s): Karma
```

Just to test things, I cloned my repository main branch, which is not an upgradeable token, redeployed my contract and was able to setup this plugin and verify the contracts I deployed without any issue - 

```
$ npx truffle run verify Migrations Karma --network ropsten
Verifying Migrations
Pass - Verified: https://ropsten.etherscan.io/address/0x8F3945eE9372CCaCDB6BF17274f15049946f0317#contracts
Verifying Karma
Pass - Verified: https://ropsten.etherscan.io/address/0x5Fd2d64C7223D2D67eA287EA1c4Cb95e03209c84#contracts
Successfully verified 2 contract(s).
```

So, if you have any advice I would appreciate it, but I have pretty much summed this up to user error on my part, Sorry for resurrecting the old issue. This seems to be on my end.

Since this is my first attempt at working on any blockchain a lot is new to me. This issue is only seen when I try to deploy the upgradeable ERC20 contract on my development branch. I think I'm getting my wires crossed in the deploy process, or I have changed something else on my `upgradeable-karma` branch that causes verification to fail.
