### ISSUE TITLE
Couldn't verify Contracts on Etherscan using truffle-plugin-verify 

### ISSUE THREAD

**Issue by metadimensions** [rkalis/truffle-plugin-verify#191]
Hello,

I can’t verify the Smart contracts on the Etherscan mainnet.  First I tried verifying directly on Etherscan but got import errors then I flattened the contract but it says the Bytecode was not matching.

<img width="1440" alt="Screenshot 2022-12-30 at 2 53 17 PM" src="https://user-images.githubusercontent.com/17061316/210076116-76d02c92-fc0c-45b7-802d-428f698f3e27.png">

Using Truffle the error says fail - **unable to verify failed to verify 1 contract(s):**

<img width="749" alt="Screenshot 2022-12-30 at 2 43 38 PM" src="https://user-images.githubusercontent.com/17061316/210076166-8dc799b9-bec4-4836-a2b7-00620b6b792f.png">

**Comment by rkalis** [comment]
Hey, thanks for the report. Do you have a repository that I can use to reproduce the issue?

**Comment by rkalis** [comment]
Also are you by any chance using `viaIR`? That is currently a known bug (see #181)

**Comment by metadimensions** [comment]
Not using ViaIR - actually the contract is already deployed on mainnet by a different dev person I couldn't find exact solidity code tried to debug this on the etherscan compiler but getting Bytecode error so trying this using Truffle verify.

**Comment by rkalis** [comment]
Oof yeah in that case it's going to be very hard to debug this because it needs to have the *exact* right source code to match. And the API response that we get from Etherscan doesn't really give you enough details to work with.

You could try using this [Truffle plugin](https://github.com/mhrsalehi/truffle-plugin-stdjsonin) to generate the Input JSON and then upload that into the Etherscan verification form. That might give you slightly better error messages. But still if you don't know exactly which code + compiler settings were used to deploy the contract it'll be **very difficult** to verify the source code.

Sorry I can't be of more assistance here. Best of luck!
