### ISSUE TITLE
Missing Comments?

### ISSUE THREAD

**Issue by conlan** [rkalis/truffle-plugin-verify#23]
Hey there! Loving this tool so far -- the only issue is that it appears that comments aren't preserved after verifying?

You can see comments here:

<img width="904" alt="Screen Shot 2019-11-26 at 12 25 10 AM" src="https://user-images.githubusercontent.com/79074/69611797-6e417d80-0fe3-11ea-8729-ad0a0f795499.png">

but not showing up on etherscan verification:

<img width="668" alt="Screen Shot 2019-11-26 at 12 24 15 AM" src="https://user-images.githubusercontent.com/79074/69611743-51a54580-0fe3-11ea-8813-91d670faa235.png">

Lemme know if you need any more details or if this is a known issue :)

**Comment by rkalis** [comment]
Hi @conlan, thanks for opening this issue. A similar point was raised by @prestwich in #15 about seemingly random linebreaks, that turned out to be removed comments. Comments are removed because truffle-plugin-verify uses [sol-merger](https://github.com/RyuuGan/sol-merger) to flatten source files, which deletes the comments.

In #15 @RyuuGan said he didn't want to implement comment parsing in sol-merger, but I can imagine that he'd be open to a good PR that adds preservation of comments.

If it's important that comments are preserved, the best way would probably be to raise such a PR to the sol-merger repository.

**Comment by conlan** [comment]
Hey @rkalis okay thanks! I've found actually the exact issue here: https://github.com/RyuuGan/sol-merger/issues/19. Will move this over there!
