### ISSUE TITLE
Support Vyper verification

### ISSUE THREAD

**Issue by lebed2045** [rkalis/truffle-plugin-verify#57]
when I try to verity vyper contract I get the error:
```
Unexpected token u in JSON at position 0
Failed to verify 1 contract(s)
```

**Comment by rkalis** [comment]
I don't think the plugin actually supports Vyper, since it uses Solidity Standard JSON, which I guess is not a thing with Vyper (haven't used Vyper myself). 

Looking at the Etherscan API documentation it looks like they only support `solidity-single-file` or `solidity-standard-json-input`, but Vyper verification looks to be possible through their web form.

I'm hoping that @Enigmatic331 or someone else at Etherscan can confirm that it's correct that Vyper verification is not supported through the API.

If it *is* somehow possible through the API then it should be possible to integrate that into the plugin, but it seems like the process for Vyper will be quite different than the one for Solidity, so I can't make any guarantees about implementing Vyper support, but I'd be open to PRs that implement it in a clean way so it fits with the rest of the plugin.

**Comment by rkalis** [comment]
I will close this issue since it's not possible to verify Vyper through the Etherscan API, but if that changes in the future, feel free to re-open this issue.
