### ISSUE TITLE
Fail - Cannot read property 'absolutePath' of undefined

### ISSUE THREAD

**Issue by arintrongs** [rkalis/truffle-plugin-verify#66]
I've got this error when trying to verify my contract.

```
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.6
Verifying TestContract
Reading artifact file at /Users/tomp/Documents/Works/test_contract/build/contracts/TestContract.json
Retrieving constructor parameters from https://api-testnet.bscscan.com/api?apiKey=xxxxxxxxxxxxxxxxxxx&module=account&action=txlist&address=0x84fd8e42B66d6C6da9584FC3513Bb71F03Da7718&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x00000000000000000000000016d57feb62d87fd8aa1c534b64dba8513252b878000000000000000000000000000000000000000000000000016345785d8a0000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000090ddd0e0387c719a367b2be6b001a333a30b85a9
Reading artifact file at /Users/tomp/Documents/Works/test_contract/build/contracts/Hasher.json
Cannot read property 'absolutePath' of undefined
Failed to verify 1 contract(s): TestContract
```

**Comment by rkalis** [comment]
Do you have a repository I can look at?

**Comment by SwirlCash** [comment]
The mentioned error can be easily reproduces for Tornado.Cash contracts - https://github.com/tornadocash/tornado-core
Hasher.json is created by an external compiler that truffle calls - https://github.com/tornadocash/tornado-core/blob/master/compileHasher.js

Can you please check if this can be verified?

**Comment by rkalis** [comment]
I see. Thanks for the link to the repo, will take a look  at it.

**Comment by rkalis** [comment]
The reason the current library linking code looks like this (looking at `ast.absolutePath`) is because the "simpler" initial version stopped working with Solidity >=0.7.5 (see the second half of the thread in [#49](https://github.com/rkalis/truffle-plugin-verify/issues/49)). Perhaps you could try installing `truffle-plugin-verify@0.5.3`, which is before I made this change.

If that doesn't work I think it *might* be possible to update the library so that it supports both cases, but I think that could be quite a bit of work, so I can't really say when I'll be able to make that work.

**Comment by SwirlCash** [comment]
This version indeed verifies the contracts right away.
Thank you for the quick response and workaround!

**Comment by rkalis** [comment]
Happy that worked. I'll try to publish a new version that works for both cases some time in the future, so I'll leave this issue open for now. But like I said, it will probably take a while.

**Comment by rkalis** [comment]
This has been open for >9 months, and at this point I think it's unlikely that I will be able to implement an update that works for both cases. If anyone finds this issue in the future, the workaround is using version `0.5.3` of the plugin or below.
