### ISSUE TITLE
Allow to verify proxy contracts

### ISSUE THREAD

**Issue by k1rill-fedoseev** [rkalis/truffle-plugin-verify#80]
Etherscan has the endpoint for verification of proxy-style contract pairs.

It would be a nice feature to allow optionally call `https://api.etherscan.io/api?module=contract&action=verifyproxycontract&apikey=YourApiKeyToken` after verification of proxy and implementations contracts separately.

I guess this can be implemented by adding an extra `--verify-proxy` flag to the `truffle run verify` command.

**Comment by rkalis** [comment]
This is interesting. I can definitely see the value in this. Will need to look into it a bit more though.

**Comment by vladlensky** [comment]
It would be really cool to implement such a feature! 

For those who are stuck with the same issue - simply pass as it is said in the docs - the real address after contract's name in the command - truffle run verify Contract@address, after that verify proxy under this URL - `https://ropsten.etherscan.io/proxyContractChecker` 

Using this URL you can even find the contract's implementation address, just paste the proxy address and it will show the implementation

But with such --verify-proxy flag it would be much easier, thank you for your plugin!

**Comment by rkalis** [comment]
I'm happy to announce that version `0.5.20`of the plugin now supports EIP1967 proxy verification out of the box 🥳 

You don't need to provide any options or anything. If you try to verify a proxy address, the plugin will verify the *implementation* instead of the proxy address, and then automatically calls Etherscan's "proxy verification" so that it gets properly marked as a proxy (with Read/Write as Proxy functionality).

Big thanks to @Danielifg for showing me his workaround, which inspired the implementation into the plugin!

**Comment by d10r** [comment]
Great feature!

I just tried it with Optimism Kovan and it mostly worked:
```
$ npx truffle run --network opkovan verify Superfluid@0x2C5Eb72F22483613fed7b241d41C7B0e35Bfb9f8
Verifying Superfluid@0x2C5Eb72F22483613fed7b241d41C7B0e35Bfb9f8
Verifying proxy implementation at 0xe62baae7a27b4a77becae654c9717b03740faff2
Pass - Verified: https://kovan-optimistic.etherscan.io/address/0x2C5Eb72F22483613fed7b241d41C7B0e35Bfb9f8#code
Successfully verified 1 contract(s).
```

Result: https://kovan-optimistic.etherscan.io/address/0x2C5Eb72F22483613fed7b241d41C7B0e35Bfb9f8#code

What's missing though: the contract was not marked proxy (the part which is triggered by "More Options -> Is this a proxy?" in the UI. This is supposed to now happen automatically, correct?

![image](https://user-images.githubusercontent.com/5479136/146229290-665257fc-88f2-4117-ae63-fccf6c62cacd.png)

**Comment by rkalis** [comment]
Oh interesting. It should have done so automatically. Could you re-run verification with the `--debug` flag and paste the output here?

**Comment by d10r** [comment]
[truffle-verify-0xDb22289a642961A603AE2e247274f2dC10cBAaB5.txt](https://github.com/rkalis/truffle-plugin-verify/files/7726095/truffle-verify-0xDb22289a642961A603AE2e247274f2dC10cBAaB5.txt)

etherscan API key replaced with ...

What hits my attention here:
```
Checking status of verification request Invalid API Key
Invalid GUID length
```

It's actually not very clear to me how the various etherscan instances do or do not share accounts / API keys.  
In this plugins, the various instances close the Ethereum (eth mainnet, eth testnets, optimism and arbitrum) share the same API key while e.g. polygonscan and snowtrace have their own API keys.  
If I try to sign in to https://optimistic.etherscan.io with the etherscan credentials I created the used API key with, that fails (https://kovan-optimistic.etherscan.io doesn't even have a sign-in button). Yet, verification with that etherscan API key seems to work in general. If I remove it and run the script, verification fails altogether.

**Comment by rkalis** [comment]
Thanks for the detailed info @d10r!

I believe that when Optimistic Etherscan was launched they didn't have any API keys. It looks like they do have separate API keys for it now, but it still doesn't check those API keys for the *regular* source code verification requests, which is why this bug didn't occur before I implemented proxy verification.

But they do check the API keys for proxy verification endpoints. So I've added some code locally to support separate keys for optimistic etherscan. But even then, when trying to call the proxy verification, I am getting "Invalid API Key" responses, even though I just generated a new API key specifically on Optimistic Etherscan.

@Enigmatic331 any chance you'd be able to shed some light on this situation?

**Comment by rkalis** [comment]
Ping @Enigmatic331

**Comment by Enigmatic331** [comment]
Ah on it right now - Will be back in a little bit

**Comment by Enigmatic331** [comment]
Sorry for the delay Rosco! We were moving some of the API key related stuff for Optimism and Arbitrum servers couple weeks back and that impacted the testnets - It should now be fixed and have also ran a test against [0xDb22289a642961A603AE2e247274f2dC10cBAaB5](https://kovan-optimistic.etherscan.io/address/0xDb22289a642961A603AE2e247274f2dC10cBAaB5#code).

Optimistic Etherscan shares an API key with its Kovan testnet, likewise Arbiscan shares one with its corresponding testnet as well, and in general should work that way across the rest of the explorers. 🙇

**Comment by rkalis** [comment]
Thanks @Enigmatic331. Just tested locally, and it's working from my end. Will publish a new release of truffle-plugin-verify next week that has support for arbiscan and optimistic etherscan API keys.
