### ISSUE TITLE
Blockscout / Ethereum Classic support

### ISSUE THREAD

**Issue by Mentors4EDU** [rkalis/truffle-plugin-verify#98]
Are there any plans for BlockScout support for massively verifying contracts? I wasn't sure what angle to go in regards to updating or making a PR and any help would be greatly appreciated.

**Comment by rkalis** [comment]
Late in 2020 I started work on splitting up the Etherscan-specific and general verification functionality in https://github.com/rkalis/truffle-plugin-verify/tree/v0.6.0. The branch is quite outdated but it shows some insight into what I wanted to achieve there. Help is definitely welcome there since I haven't been able to finish what I started. I can try to make sure the v0.6.0 is up to date with the latest changes and see from there.

**Comment by Mentors4EDU** [comment]
Yes that would be quite helpful, because I have no idea how to implement blockscout for my deployed contracts on Truffle, and hard to definitely verify manually

**Comment by Mentors4EDU** [comment]
Quick Q: Would #99 be a proper merge if the Blockscout config files are added? If not, then 0.6.0 can be pushed up to-date manually, and then the configs can be added and merged w/ main.

**Comment by rkalis** [comment]
Hey @Mentors4EDU, sorry for the late reply. I'm guessing that PR into 0.6.0 should be fine, but I'd have to spend more time on making sure it does, which can take quite some time. In any case, this issue is captured in #82, so I'll close this issue for now.
